#!/bin/bash
#This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>. 

clear
ip=$(curl -s ifconfig.me)                            
echo "your ip is ${ip}"
echo "Are you sure to flood the network [y/n]"
read response
if [[ $response == "y" ]]
then
        ping -i 0 -c 999999 -s 65027 -W 999 $ip
else
        echo "Cancelling..."
fi
